key = {
  "ql_sta": "/qmap/sqlist",
  "ql_dyn": "/qmap/dqlist",
  "dqmap": "/qmap/dqmap",
  "sqmap": "/qmap/sqmap",
  "mask": "/qmap/mask",
  "sphilist": "/qmap/sphilist",
  "dphilist": "/qmap/dphilist",
  "saxs_1d": "/xpcs/partition-mean-total",
  "Iqp": "/xpcs/partition-mean-partial",
  "tau": "/xpcs/tau",
  "g2": "/xpcs/norm-0-g2",
  "g2_err": "/xpcs/norm-0-stderr",
  "saxs_2d": "/xpcs/pixelSum",
  "Int_t": "/xpcs/frameSum",
  "c2_half": "/xpcs/C2T_all",
  "g2_full": "/xpcs/g2full",
  "g2_partials": "/xpcs/g2partials",
  "G2": "/xpcs/G2",
  "IP": "/xpcs/IP",
  "IF": "/xpcs/IF",
  "t0": "/entry/instrument/detector_1/frame_time",
  "t1": "/entry/instrument/detector_1/count_time",
}
