
key = {
  "ql_sta": "/xpcs/sqlist",
  "ql_dyn": "/xpcs/dqlist",
  "dqmap": "/xpcs/dqmap",
  "sqmap": "/xpcs/sqmap",
  "mask": "/xpcs/mask",
  "type": "/xpcs/analysis_type",
  "sphilist": "/xpcs/sphilist",
  "dphilist": "/xpcs/dphilist",
  "saxs_1d": "/exchange/partition-mean-total",
  "Iqp": "/exchange/partition-mean-partial",
  "tau": "/exchange/tau",
  "g2": "/exchange/norm-0-g2",
  "g2_err": "/exchange/norm-0-stderr",
  "saxs_2d": "/exchange/pixelSum",
  "Int_t": "/exchange/frameSum",
  "c2_half": "/exchange/C2T_all",
  "g2_full": "/exchange/g2full",
  "g2_partials": "/exchange/g2partials",
  "G2": "/exchange/G2",
  "IP": "/exchange/IP",
  "IF": "/exchange/IF",
  "t0": "/entry/instrument/detector_1/frame_time",
  "t1": "/entry/instrument/detector_1/count_time",
}
